name: BackpackJack
favicon: null
layout_spectrum: 0.9449862209148705
typography_spectrum: 0.05092366924509406
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.32197188935242593
  lightness: 0.9609122991096228
  saturation: 0.24146569892764091
  rhythmicContrast: 0.699421406025067
purpose: []
